spring:
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Shanghai
  application:
    name: product-application

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
